config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :posts
  devise_for :users
  resources :categories
  get 'home/index'

  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  # validates_presence_of :format_post

  
  belongs_to :user
  belongs_to :category

  mount_uploader :image, ImageUploader
  acts_as_taggable
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]


  def should_generate_new_friendly_id?
    title_changed?
  end

  def format_post_enum
  	['new', 'slide','hot','rising']
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :checking

  def checking
  	@categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	# @posts = Post.order("created_at DESC")
  	@new = Post.order('created_at desc').paginate(:page => params[:page], :per_page => 29)
  	@rising	 = Post.order('created_at desc').paginate(:page => params[:page], :per_page => 7)
  	@hots = Post.order('created_at desc').paginate(:page => params[:page], :per_page => 13)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!
  before_action :authenticate_user!

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :description, :format_post, :hide_post, :ads, :excerpt, :category, :user_id, :meta_title, :meta_description, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @category, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing category</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="page-header">
  <%= link_to new_category_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Category
  <% end %>
  <h1>Listing categories</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @categories) do |category| %>
            <td><%= category.name %></td>
            <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New category</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show category</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @category.name %></dd>

</dl>

app/views/home/_header.html.erb
<header id="navigation">
		<div class="navbar" role="banner">
			<div class="container">
				<a class="secondary-logo" href="index-2.html">
					<%= image_tag "logo.png", class: "img-responsive" %>		
				</a>
			</div>
			<div class="topbar">
				<div class="container">
					<div id="topbar" class="navbar-header">							

						<%= link_to root_path , class: "navbar-brand" do  %>
							 <%= image_tag "logo.png", class: "main-logo img-responsive" %>	
						<% end %>
						</a>

						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div> 
				</div> 
			</div> 
			<div id="menubar" class="container">	
				<nav id="mainmenu" class="navbar-left collapse navbar-collapse"> 
					<ul class="nav navbar-nav">             
							<% @categories.each do |cate| %>
								<li class=""><%= link_to cate.name %></li>
							<% end %>
							<li class="environment dropdown mega-dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Environment</a>
								<div class="dropdown-menu mega-menu">
									<div class="container">
										<div class="row">
											<div class="col-sm-3">
												<h2>Template Features</h2>
												<ul>
													<li><a href="#">Multi Home Variations</a></li>
													<li><a href="#">Multi Color Menu</a></li>
													<li><a href="#">Fully Responsive</a></li>
													<li><a href="#">Mega Dropdown</a></li>
													<li><a href="#">Creative Design</a></li>
												</ul>
											</div>
											<div class="col-sm-3">
												<h2>Included Pages</h2>
												<ul>
													<li><a href="news-details.html">News Details</a></li>
													<li><a href="listing.html">Category Listing</a></li>
													<li><a href="listing-life-style.html">Category Lifestyle</a></li>
													<li><a href="listing-sports.html">Category Sports</a></li>
													<li><a href="404.html">404 Error</a></li>
												</ul>
											</div>
											<div class="col-sm-3">
												<h2>Menu with image</h2>
												<div class="entry-thumbnail">
													<img class="img-responsive" src="assets/4.jpg" alt="" /> 
												</div>												
											</div>
											<div class="col-sm-3">
												<h2>Menu with video</h2>
												<div class="entry-thumbnail embed-responsive embed-responsive-16by9">
													<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/-WlqrkXImsk" allowfullscreen></iframe>
												</div>
											</div>
										</div>
									</div>
								</div>
							</li>
				
							<li class="more dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Pages +</a>
								<ul class="dropdown-menu">
									<li><a href="contact-us.html">Contact Us <span class="badge">New</span></a></li>
									<li><a href="contact-us2.html">Contact Us Two <span class="badge">New</span></a></li>
									<li><a href="signup.html">Sign Up Page<span class="badge">New</span></a></li>
									<li><a href="signin.html">Sign In page<span class="badge">New</span></a></li>
								</ul>
							</li>
						
					</ul> 					
				</nav>
				<div class="searchNlogin">
					<ul>
						<li class="search-icon"><i class="fa fa-search"></i></li>
						<!-- <li class="dropdown user-panel"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i></a>
							<div class="dropdown-menu top-user-section">
								<div class="top-user-form">
									<form id="top-login" role="form">
										<div class="input-group" id="top-login-username">
											<span class="input-group-addon"><img src="assets/others/user-icon.png" alt="" /></span>
											<input type="text" class="form-control" placeholder="Username" required="">
										</div>
										<div class="input-group" id="top-login-password">
											<span class="input-group-addon"><img src="assets/others/password-icon.png" alt="" /></span>
											<input type="password" class="form-control" placeholder="Password" required="">
										</div>
										<div>
											<p class="reset-user">Forgot <a href="#">Password/Username?</a></p>
											<button class="btn btn-danger" type="submit">Login</button>
										</div>
									</form>
								</div>
								<div class="create-account">
									<a href="#">Create a New Account</a>
								</div>
							</div>
						</li> -->
					</ul>
					<div class="search">
						<form role="form">
							<input type="text" class="search-form" autocomplete="off" placeholder="Searching...">
						</form>
					</div> <!--/.search--> 
				</div><!-- searchNlogin -->
			</div>
		</div>
	</header><!--/#navigation--> 

app/views/home/_latest.html.erb
<div class="section">				
		<div class="latest-news-wrapper">
			<h1 class="section-title">Latest News</h1>	
			<div id="latest-news">
				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/1.jpg" alt="" />
						</div>
						<div class="catagory politics"><span><a href="#">Politics</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">Our closest relatives aren't fans of daylight saving time</a>
						</h2>
					</div>
				</div><!--/post--> 
				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/2.jpg" alt="" />
						</div>
						<div class="catagory world"><a href="#">World</a></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">44 books on 44 presidents: Welcome, folks, to the Adams</a>
						</h2>
					</div>
				</div><!--/post--> 
				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/4.jpg" alt="" />
						</div>
						<div class="catagory health"><span><a href="#">Health</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">And the most streamed Beatles song on Spotify is...</a>
						</h2>
					</div>
				</div><!--/post--> 

				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/3.jpg" alt="" />
						</div>
						<div class="catagory sports"><span><a href="#">Sports</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">NBA suspends Matt Barnes for attack on Derek Fisher</a>
						</h2>
					</div>
				</div><!--/post--> 

				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/5.jpg" alt="" />
						</div>
						<div class="catagory politics"><span><a href="#">Politics</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">At Facebook who suggests tags for all of your photos</a>
						</h2>
					</div>
				</div><!--/post--> 

				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/6.jpg" alt="" />
						</div>
						<div class="catagory entertainment"><span><a href="#">Entertainment</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">Suspicion of plotting New Year's Eve attacks in Belgium</a>
						</h2>
					</div>
				</div><!--/post--> 
				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/9.jpg" alt="" />
						</div>
						<div class="catagory sports"><span><a href="#">Sports</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">Someone has calculated the total cost of saving Matt</a>
						</h2>
					</div>
				</div><!--/post--> 

				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/8.jpg" alt="" />
						</div>
						<div class="catagory politics"><span><a href="#">Politics</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">Homemade lightsaber made with laser can cut wires</a>
						</h2>
					</div>
				</div><!--/post--> 

				<div class="post medium-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
							<img class="img-responsive" src="assets/10.jpg" alt="" />
						</div>
						<div class="catagory entertainment"><span><a href="#">Entertainment</a></span></div>
					</div>
					<div class="post-content">								
						<div class="entry-meta">
							<ul class="list-inline">
								<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 5, 2015 </a></li>
								<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
								<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
							</ul>
						</div>
						<h2 class="entry-title">
							<a href="news-details.html">Our closest relatives aren't fans of daylight saving time</a>
						</h2>
					</div>
				</div><!--/post--> 
			</div>
		</div><!--/.latest-news-wrapper-->
	</div><!--/.section-->

app/views/home/_rightbar.html.erb
<div class="middle-content">
									<div class="section sports-section">
										<h1 class="section-title title">What's Hot</h1>

										<% @hots.each do |post| %>
											<%# if post.format_post == "hot" %>
												<div class="post medium-post">
													<div class="entry-header">
														<div class="entry-thumbnail">

														<img class="img-responsive" src="assets/post/2.jpg" alt="">
															<%#= image_tag post.image, class: "img-responsive" %>
														</div>
													</div>
													<div class="post-content">								
														<div class="entry-meta">
															<ul class="list-inline">
																<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i> Nov 15, 2015 </a></li>
																<li class="views"><a href="#"><i class="fa fa-eye"></i>15k</a></li>
																<li class="loves"><a href="#"><i class="fa fa-heart-o"></i>278</a></li>
															</ul>
														</div>
														<h2 class="entry-title">
															<%= link_to post.title, root_path %>
														</h2>
													</div>
												</div><!--/post--> 
											<%# end %>
										<% end %>

									</div><!--/.sports-section -->

								<!--<div class="section">
										<div class="add inner-add">
											<a href="#"><img class="img-responsive" src="assets/add/add5.jpg" alt="" /></a>
										</div>
									</div>
									 -->

								</div><!--/.middle-content-->

app/views/home/_sidebar.html.erb
<div class="widget">
	<h1 class="section-title title">What's New</h1>
	<ul class="post-list">
		<% @new.each do |post| %>
			<%# if post.format_post == "new" %>
			<li>
				<div class="post small-post">
					<div class="entry-header">
						<div class="entry-thumbnail">
						<img class="img-responsive" src="assets/rising/8.jpg" alt="">
							<%#= image_tag post.image, size: "150", class: "img-responsive" %>
						</div>
					</div>
					<div class="post-content">								
						<div class="video-catagory"><a href="#">World</a></div>
						<h2 class="entry-title">
							<%= link_to post.title %>
						</h2>
					</div>
				</div><!--/post--> 
			</li>
			<%# end %>
		<% end %>
	</ul>
</div><!--/#widget-->	

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Post
  <% end %>
  <h1>Listing posts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Image</th>
            <th>Description</th>
            <th>Format post</th>
            <th>Hide post</th>
            <th>Ads</th>
            <th>Excerpt</th>
            <th>Category</th>
            <th>User</th>
            <th>Meta title</th>
            <th>Meta description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @posts) do |post| %>
            <td><%= post.title %></td>
            <td><%= post.image %></td>
            <td><%= post.description %></td>
            <td><%= post.format_post %></td>
            <td><%= post.hide_post %></td>
            <td><%= post.ads %></td>
            <td><%= post.excerpt %></td>
            <td><%= post.category %></td>
            <td><%= post.user %></td>
            <td><%= post.meta_title %></td>
            <td><%= post.meta_description %></td>
            <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show post</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @post.title %></dd>

  <dt>Image:</dt>
  <dd><%= @post.image %></dd>

  <dt>Description:</dt>
  <dd><%= @post.description %></dd>

  <dt>Format post:</dt>
  <dd><%= @post.format_post %></dd>

  <dt>Hide post:</dt>
  <dd><%= @post.hide_post %></dd>

  <dt>Ads:</dt>
  <dd><%= @post.ads %></dd>

  <dt>Excerpt:</dt>
  <dd><%= @post.excerpt %></dd>

  <dt>Category:</dt>
  <dd><%= @post.category %></dd>

  <dt>User:</dt>
  <dd><%= @post.user %></dd>

  <dt>Meta title:</dt>
  <dd><%= @post.meta_title %></dd>

  <dt>Meta description:</dt>
  <dd><%= @post.meta_description %></dd>

</dl>